careers/careers/urls.py
from django.conf.urls.defaults import patterns, url

from . import views


urlpatterns = patterns('',
    url(r'^position/(?P<job_id>[\w]+)$', views.position,
        name='careers.position'),
    url(r'^position/(?P<job_id>[\w]+)$', views.position,
        name='django_jobvite_position'),
    url(r'^$', views.home, name='careers.home'),
    url(r'^listings/$', views.listings, name='careers.listings'),
)

careers/careers/forms.py
from django import forms

from django_jobvite.models import Category, Position


class PositionFilterForm(forms.Form):
    team = forms.ModelChoiceField(queryset=Category.objects.order_by('name'),
                                  empty_label='All Teams',
                                  widget=forms.Select(attrs={'autocomplete': 'off'}))
    position_type = forms.ChoiceField(widget=forms.Select(attrs={'autocomplete': 'off'}))
    location = forms.ChoiceField(choices=(
        ('', 'All Locations'),
        ('remote', 'Remote'),

        # Continents
        ('europe', 'Europe'),
        ('latinamerica', 'Latin America'),
        ('northamerica', 'North America'),

        # Young money
        ('bayarea', 'Bay Area'),

        # Cities
        ('berlin', 'Berlin'),
        ('boston', 'Boston'),
        ('london', 'London'),
        ('mountainview', 'Mountain View'),
        ('newzealand', 'New Zealand'),
        ('paris', 'Paris'),
        ('portland', 'Portland'),
        ('sanfrancisco', 'San Francisco'),
        ('toronto', 'Toronto'),
        ('vancouver', 'Vancouver'),
    ), widget=forms.Select(attrs={'autocomplete': 'off'}))

    def __init__(self, *args, **kwargs):
        super(PositionFilterForm, self).__init__(*args, **kwargs)

        # Populate position type choices dynamically.
        types = Position.objects.values_list('job_type', flat=True).distinct().order_by('job_type')
        self.fields['position_type'].choices = [('', 'All Positions')] + [(k, k) for k in types]

careers/careers/views.py
from django.http import Http404
from django.shortcuts import render

from django_jobvite.models import Position

from careers.careers.forms import PositionFilterForm


def home(request):
    return render(request, 'careers/home.html')


def listings(request):
    return render(request, 'careers/listings.html', {
        'positions': Position.objects.order_by('category__name', 'title'),
        'form': PositionFilterForm(request.GET or None),
    })


def position(request, job_id=None):
    try:
        position = Position.objects.select_related('category').get(job_id__contains=job_id)
        positions = position.category.position_set.all()

        # Add applicant source param for jobvite
        position.apply_url += '&s=PDN'

        return render(request, 'careers/position.html', {
            'position': position,
            'positions': positions,
        })
    except Position.DoesNotExist:
        raise Http404

careers/careers/templates/careers/listings.html
{% extends "base.html" %}

{% set navbar_section = 'listings' %}
{% block page_title %}Listings{% endblock %}

{% block site_css %}
  {{ super() }}
  {{ css('listings') }}
{% endblock %}

{% block site_ie8 %}
  {{ super() }}
  {{ css('listings-ie8') }}
{% endblock %}

{% block site_js %}
  {{ super() }}
  <!--[if gt IE 8]> <!-- -->
    {{ js('listings') }}
  <!-- <![endif]-->
  {{ js('filters') }}
{% endblock %}

{% block content %}

<section id="listings-intro">
  <h2 class="listings-intro-head">Careers at Mozilla</h2>
  <p class="listings-intro-body">
    Below is our current list of job openings, available internships and contract opportunities. Have a look around and if there’s one that fits you, please apply. If not, keep checking back. Good luck.
  </p>
</section>

<section id="listings">
  <div class="contain">
    <h2 class="listings-head">Listings</h2>

    <form id="listings-filters">
      <h3 class="listings-filters-head">Filter by</h3>
      <div class="listings-filter listings-filter-location">
        {{ form.location }}
        <label for="id_location">Location</label>
      </div>
      <div class="listings-filter listings-filter-type">
        {{ form.position_type }}
        <label for="id_position_type">Position Type</label>
      </div>
      <div class="listings-filter listings-filter-name">
        {{ form.team }}
        <label for="id_team">Team</label>
      </div>
    </form>

    <table id="listings-positions">
      <thead>
        <tr>
          <th class="title" scope="col">Job Title</th>
          <th class="location" scope="col">Location</th>
          <th class="type" scope="col">Position</th>
          <th class="name" scope="col">Team</th>
        </tr>
      </thead>
      <tbody>
      {% for position in positions %}
        <tr class="position"
            data-team="{{ position.category.id }}"
            data-type="{{ position.job_type }}"
            data-location="{{ position.location_filter }}">
          <td class="title"><a href="{{ position.get_absolute_url() }}">{{ position.title }}</a></td>
          <td class="location">{{ position.location_filter }}</td>
          <td class="type">{{ position.job_type }}</td>
          <td class="name">{{ position.category.name }}</td>
        </tr>
      {% endfor %}
        <tr class="empty-filter-message hidden">
          <td colspan="4">
            <p>No jobs found that match the selected filters.</p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</section>
{% endblock %}

careers/careers/templates/careers/macros.html
{% macro breadcrumbs() -%}
  <header id="jobs-header">
    <p id="breadcrumbs">
      <a href="http://www.mozilla.org/{{ LANG }}" class="home">Home</a>
      <strong>»</strong>
      <a href="http://www.mozilla.org/{{ LANG }}/about">About</a>
      <strong>»</strong>
      {% for crumb in varargs -%}
        <a href="{{ crumb[0] }}">{{ crumb[1] }}</a>
        <strong>»</strong>
      {% endfor -%}
      <span>{{ kwargs.last }}</span>
    </p>
  </header>
{% endmacro -%}

{% macro position_listing(category) -%}
  <li>
    <h2>{{ category.name }}</h2>
    <ul>
      {% for position in category.position_set.order_by('title') %}
        <li>
          <a href="{{ url('careers.position', job_id=position.job_id) }}"
             data-jobtype="{{ position.job_type.lower() }}"
             alt="{{ position.title }}"
             title="{{ position.title }}">{{ position.title }}</a>
        </li>
      {% endfor %}
    </ul>
  </li>
{% endmacro -%}

careers/careers/templates/careers/position.html
{% extends "base.html" %}

{% block page_title %}{{ '{position} &mdash; Mozilla Jobs &mdash; Open Positions'|f(position=position.title)|safe }}{% endblock %}

{% block site_css %}
  {{ super() }}
  {{ css('position') }}
{% endblock %}

{% block content %}
<section id="job">

    <article id="job-post" class="job-post" data-location-filter="{{ position.location_filter }}">
      <div class="job-post-head">
        <div class="contain">
          <h1 class="job-post-title">{{ position.title }}</h1>
          <a class="cta job-post-head-apply ga-job-listing-apply" href="{{ position.apply_url|urlparams(utm_source='careers.mozilla.org', utm_medium='referral') }}">Apply for this job</a>
          <dl class="job-post-details">
            <dt class="job-post-team-head">Team:</dt>
            <dd class="job-post-team">{{ position.category.name }}</dd>
            <dt class="job-post-location-head">Locations:</dt>
            <dd class="job-post-location">{{ position.location|default('All', True) }}</dd>
          </dl>
        </div>
      </div>

      <div class="contain">
        <div class="job-post-description">
          {#
            Description is bleached through
            django-jobvite so it will be
            happy here.
          #}
          {{ position.description|safe }}
        </div>
        <aside class="job-related">
          <h2 class="job-related-head">{{ position.category.name }}: {{ _('Open Positions') }}</h2>
          <ul class="job-related-list">
            {% for p in positions if p != position %}
              <li>
                <a href="{{ url('careers.position', p.job_id) }}"
                   class="{% if position.job_id == p.job_id %}active{% endif %} ga-job-listing-detail"
                   title="{{ p.title }}">{{ p.title }}</a>
              </li>
            {% endfor %}
          </ul>
        </aside>
      </div>
    </article>
  </div>
  <a id="job-post-apply" class="cta ga-job-listing-apply" href="{{ position.apply_url|urlparams(utm_source='careers.mozilla.org', utm_medium='referral') }}">Apply for this job</a>
</section>

<section id="why">
  <div class="contain">
    <h2 class="why-head">Why Mozilla?</h2>
    <div class="why-intro">
      <p>
        Mozilla is a thriving global community of technologists, thinkers and builders working collaboratively and openly to keep the Internet alive and accessible for all. When you work at Mozilla, you give yourself a chance to make a difference in the lives of Web users everywhere. And you give us a chance to make a difference in your life every day. Join our team today and together we’ll make a better Web for tomorrow.
      </p>
    </div>

    <div class="why-reasons">
      <div class="why-reason-box">
        <h3>We Are Global</h3>
        <ul>
          <li>500+ paid staff from over 30 countries</li>
          <li>Thousands of active contributors across six continents</li>
          <li>13 global offices: Mountain View, San Francisco, Portland, Boston, Vancouver, Toronto, Auckland, Paris, London, Berlin, Beijing, Tokyo, and Taipei</li>
          <li>Hundreds of home offices and remote workers around the world</li>
        </ul>
      </div>
      <div class="why-reason-box">
        <h3>And so are our benefits...</h3>
        <ul>
          <li>Competitive pay</li>
          <li>Top-notch medical</li>
          <li>Travel and conference budgets</li>
          <li>Ability to work using the latest hardware and software of your choice</li>
          <li>Dozens of technical Lunch and Learns and invited speakers each month</li>
        </ul>
      </div>
      <div class="why-reason-box">
        <h3>Because we love what we do!</h3>
        <ul>
          <li>We take bold technical leaps</li>
          <li>We code and ship in the open</li>
          <li>We directly impact hundreds of millions of users</li>
          <li>We build technology for the benefit of the Web’s users and creators</li>
          <li>We work in a culture defined by principles over profits</li>
        </ul>
      </div>
    </div>
  </div>
</section>

{% endblock %}